name: artifacts.builder

on:
  workflow_call:

env:
  SLN_PATH: .\Up2dateService\Up2dateService.sln
  ARTIFACTS_PATH_X32: .\Up2dateService\Setup32\Release\
  ARTIFACTS_PATH_X64: .\Up2dateService\Setup64\Release\
  ARTIFACTS_PATH_TESTS: .\Up2dateService\Tests\Up2dateTests\bin\Release\
  
jobs:
  artifacts:
    name: Building artifacts
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v2.0.0
      with:
       args: install checksum
      - name: Prepare Choco Package
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            cd .\package\
            $content=(Get-Content -path .\\tools\\chocolateyinstall.ps1 -Raw)
            $checksum=(checksum -t sha256 -f .\\tools\\Up2dateSetup32.msi)
            $replaceTo="checksum      = '$checksum'"
            $replaced=$content -replace 'checksum      = ''(.*)''',$replaceTo
            $checksum=(checksum -t sha256 -f .\\tools\\Up2dateSetup64.msi)
            $content=$replaced
            $replaceTo="checksum64    = '$checksum'"
            $replaced=$content -replace 'checksum64    = ''(.*)''',$replaceTo
            echo $replaced | Set-Content -Path .\\tools\\chocolateyinstall.ps1
            choco pack

      - name: Upload choco package artifacts
        uses: actions/upload-artifact@v3
        with:
          path: .\packages\*.nupkg
          

      - name: Upload Test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test
          path: ${{ env.ARTIFACTS_PATH_TESTS }}
